name: Кабинет наставника
description: Проблемы, вопросы, предложения, связанные с кабинетом наставника
title: '[tutor] '
labels: ['category: tutor']
# assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        В заголовке краткой фразой опишите проблему.
        Например:
        ```
        [tutor] Недоступна страница выбора курса
        ```
  - type: input
    attributes:
      label: Ссылка
      description: Укажите адрес страницы, о которой идёт речь.
      placeholder: https://htmlacademy.ru/tutor/buy/intensive
    validations:
      required: true
  - type: textarea
    attributes:
      label: Проблема или вопрос
      description: Максимально подробно опишите проблему, с которой вы столкнулись, или ваше предложение по улучшению продуктов Академии
  - type: textarea
    id: device-info
    attributes:
      label: Информация об устройстве
      description: |
        Укажите версию браузера и операционной системы вашего устройства.
        Напрмер:
        ```
        - Девайс: iPhone6
        - ОС: iOS8.1
        - Браузер: stock browser, safari
        - Версия: 22
        ```
      value: |
        - Девайс:
        - ОС:
        - Браузер:
        - Версия:
  - type: textarea
    id: more-info
    attributes:
      label: Дополнительная информация
      description: Можете добавить любую информацию, которая ускорит решение указанной проблемы.
  - type: textarea
    id: proposal
    attributes:
      label: Возможное решение или предложение по улучшению
      description: Если есть предложение по решению проблемы, опишите его. Если вариантов несколько, перечислите их.
